default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

production:
  <<: *default
  database: {{cookiecutter.project_kebab}}_production

development:
  <<: *default
  database: {{cookiecutter.project_kebab}}_development

test:
  <<: *default
  database: {{cookiecutter.project_kebab}}_test
