version: '3.7'
services:
  db:
    image: postgres:12.3
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Insecure connection, only for local
    networks:
      - backend
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.web
    init: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db
      - webpacker
    networks:
      - backend
      - frontend
  webpacker:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.web
    init: true
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3035:3035"
    networks:
      - frontend

volumes:
  data:
    driver: local

networks:
  backend:
  frontend:
